
steps:
pool:
  vmImage: 'vs2017-win2016' # other options: 'macOS-10.13', 'vs2017-win2016'
# Restore NuGet packages
- task: DotNetCoreInstaller@0
  inputs:
    version: '4.7.02558' # replace this value with the version that you need for your project
- script: dotnet restore
- script: dotnet build # Include additional options such as --configuration to meet your need
- script: dotnet tool install -g dotnetsay
- script: dotnetsay
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: PublishBuildArtifacts@1
- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True
    
